# Generated by Django 4.2.2 on 2023-06-12 12:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('desirable', models.BooleanField(default=False, verbose_name='Желательно')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('fixed_time', models.BooleanField(default=False, verbose_name='Фиксированное время')),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='offers.category', verbose_name='Категории')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='locations.location', verbose_name='Место')),
                ('options', models.ManyToManyField(blank=True, related_name='offers', to='offers.option', verbose_name='Опции')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('only_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None, verbose_name='Только эти даты')),
                ('except_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None, verbose_name='Кроме этих дат')),
                ('except_weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='Кроме этих дней недели')),
                ('open_time', models.TimeField(verbose_name='Время начала (открытия)')),
                ('close_time', models.TimeField(verbose_name='Время окончания (закрытия)')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='offers.offer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календари',
            },
        ),
    ]
