# Generated by Django 4.2.2 on 2023-06-30 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_calendar_price_offer_grade_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='only_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='Только эти дни недели'),
        ),
    ]
