# Generated by Django 4.2.2 on 2023-07-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reservation',
            field=models.BooleanField(default=False, verbose_name='Требуется резервирование мест'),
        ),
    ]
