# Generated by Django 4.2.2 on 2023-07-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0005_offer_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('status', models.CharField(choices=[('FOUND', 'Найдено'), ('PAID', 'Оплачено'), ('RESERVED', 'Зарезервировано'), ('DONE', 'Выполнено'), ('CANCELLED', 'Отменено'), ('EXPIRED', 'Просрочен')], default='FOUND', max_length=16, verbose_name='Статус')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='offers.offer', verbose_name='Предложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
    ]
